# Generated by Django 5.2.6 on 2026-09-27 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashPayoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_holder', models.CharField(blank=True, max_length=160)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('cheque', 'Cheque / Current'), ('savings', 'Savings'), ('business', 'Business'), ('transmission', 'Transmission')], default='cheque', max_length=20)),
                ('payout_reference', models.CharField(blank=True, max_length=120)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_profile', to='carwash.carwashbusiness')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
