# Generated by Django 5.2.6 on 2026-09-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_carwashpayoutprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashbusiness',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, editable=False, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='carwashbusiness',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, editable=False, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='carwashproviderlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='carwashproviderlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='carwashquote',
            name='service_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='carwashquote',
            name='service_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='carwashstatushistory',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='carwashstatushistory',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
