# Generated by Django 5.2.6 on 2026-09-29 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_alter_carwashbusiness_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashSafetyReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('safety', 'Safety concern'), ('harassment', 'Harassment or threatening behaviour'), ('fraud', 'Suspected fraud or scam'), ('property', 'Property or vehicle incident'), ('no_show', 'No-show / location concern'), ('other', 'Other')], default='safety', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('reporter_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('reporter_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('reported_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('reported_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('nearest_police_name', models.CharField(blank=True, max_length=180)),
                ('nearest_police_address', models.CharField(blank=True, max_length=255)),
                ('nearest_police_place_id', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='carwash.carwashbusiness')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carwash_safety_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carwash_safety_reports_made', to=settings.AUTH_USER_MODEL)),
                ('wash_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='carwash.carwashrequest')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='carwash.carwashworker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
