# Generated by Django 5.2.6 on 2026-08-09 07:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realestate', '0005_property_average_rating_property_dislikes_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.adcategory')),
            ],
            options={
                'verbose_name_plural': 'Ad Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ad_type', models.CharField(choices=[('property', 'Property'), ('service', 'Service'), ('promotion', 'Promotion'), ('event', 'Event'), ('brand', 'Brand Awareness'), ('other', 'Other')], default='promotion', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/%Y/%m/%d/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if no image uploaded')),
                ('video_url', models.URLField(blank=True, help_text='Video URL (YouTube, Vimeo, etc.)')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail for video ads')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('price_currency', models.CharField(default='ZAR', max_length=10)),
                ('display_price', models.CharField(blank=True, help_text="Custom price display (e.g., 'From R2,500,000')", max_length=100)),
                ('target_audience', models.JSONField(blank=True, default=dict, help_text='Targeting criteria (age, gender, interests, etc.)')),
                ('target_locations', models.JSONField(blank=True, default=list, help_text='List of target locations')),
                ('target_property_types', models.JSONField(blank=True, default=list, help_text='List of property types to target')),
                ('target_user_types', models.JSONField(blank=True, default=list, help_text='List of user types to target')),
                ('target_min_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_max_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_impressions', models.IntegerField(blank=True, help_text='Maximum number of impressions', null=True)),
                ('max_clicks', models.IntegerField(blank=True, help_text='Maximum number of clicks', null=True)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_daily', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_per_click', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_impression', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_conversion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impressions', models.IntegerField(default=0)),
                ('unique_impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('unique_clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ctr', models.DecimalField(decimal_places=2, default=0, help_text='Click Through Rate %', max_digits=5)),
                ('position', models.CharField(choices=[('feed', 'Feed'), ('sidebar', 'Sidebar'), ('top', 'Top Banner'), ('bottom', 'Bottom Banner'), ('popup', 'Popup'), ('both', 'Both')], default='feed', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('frequency_cap', models.IntegerField(default=0, help_text='Max times per user per day (0 = unlimited)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('cta_text', models.CharField(default='Learn More', max_length=50)),
                ('cta_link', models.URLField(blank=True)),
                ('cta_button_color', models.CharField(default='#8a2be2', max_length=20)),
                ('cta_button_text_color', models.CharField(default='#ffffff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ads', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='realestate.property')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='ads.adcategory')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('converted', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='ads.ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AdConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('conversion_type', models.CharField(blank=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_records', to='ads.ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-converted_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_records', to='ads.ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ads.ad')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AdTargetingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('location', 'Location'), ('property_type', 'Property Type'), ('user_type', 'User Type'), ('interest', 'Interest'), ('behavior', 'Behavior'), ('custom', 'Custom')], max_length=50)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('in', 'In List'), ('not_in', 'Not In List'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('between', 'Between')], max_length=20)),
                ('value', models.JSONField(help_text='Rule value(s)')),
                ('is_active', models.BooleanField(default=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeting_rules', to='ads.ad')),
            ],
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'is_active'], name='ads_ad_status_a97065_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['start_date', 'end_date'], name='ads_ad_start_d_26c3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['position', 'priority'], name='ads_ad_positio_7d4a16_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['advertiser', 'status'], name='ads_ad_adverti_03ff63_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['ad', 'clicked_at'], name='ads_adclick_ad_id_f0e6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['session_id'], name='ads_adclick_session_4120ae_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['user', 'clicked_at'], name='ads_adclick_user_id_2f0ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='adconversion',
            index=models.Index(fields=['ad', 'converted_at'], name='ads_adconve_ad_id_ea952d_idx'),
        ),
        migrations.AddIndex(
            model_name='adconversion',
            index=models.Index(fields=['session_id'], name='ads_adconve_session_eb1e74_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['ad', 'viewed_at'], name='ads_adimpre_ad_id_ff249d_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['session_id'], name='ads_adimpre_session_9c8100_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['user', 'viewed_at'], name='ads_adimpre_user_id_be3305_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adschedule',
            unique_together={('ad', 'day_of_week')},
        ),
    ]
