# hiring/utils/property_config.py

PROPERTY_CONFIGS = {
    'land_sale': {
        'title': 'Land for Sale',
        'icon': 'fa-map',
        'badge_color': 'success',
        'description': 'List vacant land, farms, or agricultural land',
        'required_fields': ['title', 'description', 'price', 'location', 'land_size_hectares'],
        'show_fields': {
            'basic': ['title', 'description', 'price', 'location'],
            'land': ['land_size_hectares', 'land_size_acres', 'land_use', 'zoning', 
                    'soil_type', 'topography', 'water_access', 'electricity_access', 
                    'road_access', 'development_potential'],
            'sale': ['bond_available', 'transfer_duty', 'registration_fees', 'levies', 'rates_taxes'],
        },
        'hidden_fields': [
            'minimum_stay', 'maximum_stay', 'stay_type', 'booking_unit',
            'deposit_amount', 'lease_duration_months', 'notice_period_days',
            'utilities_included', 'maintenance_fee',
            'student_accommodation_type', 'semester_duration_months',
            'is_per_student_pricing', 'per_student_price', 'includes_meals',
            'commercial_type', 'number_of_floors', 'parking_available',
            'loading_bays', 'ceiling_height',
        ],
        'field_labels': {
            'land_size_hectares': 'Land Size (Hectares)',
            'land_size_acres': 'Land Size (Acres)',
            'land_use': 'Land Use / Zoning Purpose',
            'zoning': 'Zoning Classification',
            'soil_type': 'Soil Type',
            'topography': 'Topography',
            'water_access': 'Water Access Available',
            'electricity_access': 'Electricity Access Available',
            'road_access': 'Road Access Type',
            'development_potential': 'Development Potential',
        },
        'field_placeholders': {
            'land_size_hectares': 'e.g., 5.5',
            'zoning': 'e.g., Agricultural Zone 1',
            'soil_type': 'e.g., Sandy Loam',
        },
        'field_help_texts': {
            'land_size_hectares': 'Total land size in hectares',
            'water_access': 'Is there water access on the property?',
        },
        'show_pricing_options': True,
        'show_booking_options': False,
        'show_lease_options': False,
        'show_sale_options': True,
        'sections': ['Basic Information', 'Land Details', 'Sale Information'],
        'default_status': 'available',
        'listing_types': ['sale'],
        'requires_land_fields': True,
    },
    'student_accommodation': {
        'title': 'Student Accommodation',
        'icon': 'fa-graduation-cap',
        'badge_color': 'info',
        'description': 'List student housing near campuses',
        'required_fields': ['title', 'description', 'price', 'location'],
        'show_fields': {
            'basic': ['title', 'description', 'price', 'location', 'bedrooms', 'bathrooms'],
            'student': ['student_accommodation_type', 'semester_duration_months', 
                       'is_per_student_pricing', 'per_student_price', 'includes_meals',
                       'includes_internet', 'includes_study_area', 'proximity_to_campus',
                       'shuttle_service', 'security_guards', 'cctv_cameras'],
            'stay': ['stay_type', 'minimum_stay', 'maximum_stay', 'booking_unit', 
                    'deposit_amount', 'lease_duration_months'],
        },
        'hidden_fields': [
            'land_size_hectares', 'land_size_acres', 'land_use', 'zoning',
            'soil_type', 'topography', 'water_access', 'electricity_access',
            'road_access', 'development_potential',
            'commercial_type', 'number_of_floors', 'parking_available',
            'loading_bays', 'ceiling_height',
            'bond_available', 'transfer_duty', 'registration_fees',
        ],
        'field_labels': {
            'student_accommodation_type': 'Accommodation Type',
            'semester_duration_months': 'Semester Duration (months)',
            'is_per_student_pricing': 'Price Per Student',
            'per_student_price': 'Price Per Student (ZAR)',
            'includes_meals': 'Meals Included',
            'includes_internet': 'Internet Included',
            'includes_study_area': 'Study Area Included',
            'proximity_to_campus': 'Proximity to Campus',
            'shuttle_service': 'Shuttle Service',
            'security_guards': 'Security Guards',
            'cctv_cameras': 'CCTV Security',
            'stay_type': 'Rental Type',
            'minimum_stay': 'Minimum Stay (days)',
            'booking_unit': 'Price Per',
            'deposit_amount': 'Deposit Amount (ZAR)',
            'lease_duration_months': 'Lease Duration (months)',
        },
        'field_placeholders': {
            'student_accommodation_type': 'e.g., Dormitory, Apartment',
            'semester_duration_months': 'e.g., 6',
            'per_student_price': 'e.g., 5500',
            'proximity_to_campus': 'e.g., 5 min walk',
            'minimum_stay': 'e.g., 30',
        },
        'field_help_texts': {
            'semester_duration_months': 'Standard semester length in months',
            'is_per_student_pricing': 'Price is per student, not per room',
        },
        'show_pricing_options': True,
        'show_booking_options': True,
        'show_lease_options': True,
        'show_sale_options': False,
        'sections': ['Basic Information', 'Student Housing Details', 'Stay & Booking'],
        'default_status': 'available',
        'listing_types': ['rent', 'booking'],
        'requires_land_fields': False,
        'stay_type_default': 'monthly',
        'booking_unit_default': 'month',
        'minimum_stay_default': 30,
    },
    'short_stay': {
        'title': 'Short Stay / Vacation Rental',
        'icon': 'fa-bed',
        'badge_color': 'warning',
        'description': 'List vacation rentals and short-term accommodation',
        'required_fields': ['title', 'description', 'price', 'location', 'minimum_stay'],
        'show_fields': {
            'basic': ['title', 'description', 'price', 'location', 'bedrooms', 'bathrooms'],
            'stay': ['stay_type', 'minimum_stay', 'maximum_stay', 'booking_unit', 
                    'deposit_amount', 'pets_allowed', 'furnishing_status'],
        },
        'hidden_fields': [
            'land_size_hectares', 'land_size_acres', 'land_use', 'zoning',
            'soil_type', 'topography', 'water_access', 'electricity_access',
            'road_access', 'development_potential',
            'commercial_type', 'number_of_floors', 'parking_available',
            'loading_bays', 'ceiling_height',
            'lease_duration_months', 'notice_period_days', 'utilities_included',
            'maintenance_fee', 'rental_increase_percentage',
            'student_accommodation_type', 'semester_duration_months',
            'is_per_student_pricing', 'per_student_price',
            'bond_available', 'transfer_duty', 'registration_fees',
        ],
        'field_labels': {
            'stay_type': 'Stay Type',
            'minimum_stay': 'Minimum Stay (days)',
            'maximum_stay': 'Maximum Stay (days)',
            'booking_unit': 'Price Per',
            'deposit_amount': 'Security Deposit (ZAR)',
            'pets_allowed': 'Pets Allowed',
            'furnishing_status': 'Furnishing Status',
        },
        'field_placeholders': {
            'minimum_stay': 'e.g., 1',
            'maximum_stay': 'e.g., 90',
            'deposit_amount': 'e.g., 2000',
        },
        'field_help_texts': {
            'minimum_stay': 'Minimum number of days for a booking',
            'maximum_stay': 'Maximum number of days (leave blank for unlimited)',
        },
        'show_pricing_options': True,
        'show_booking_options': True,
        'show_lease_options': False,
        'show_sale_options': False,
        'sections': ['Basic Information', 'Stay Details'],
        'default_status': 'available',
        'listing_types': ['booking'],
        'requires_land_fields': False,
        'stay_type_default': 'daily',
        'booking_unit_default': 'day',
        'minimum_stay_default': 1,
    },
    'long_stay': {
        'title': 'Long Stay / Rental',
        'icon': 'fa-home',
        'badge_color': 'primary',
        'description': 'List long-term rentals and properties for lease',
        'required_fields': ['title', 'description', 'price', 'location'],
        'show_fields': {
            'basic': ['title', 'description', 'price', 'location', 'bedrooms', 'bathrooms'],
            'stay': ['stay_type', 'minimum_stay', 'booking_unit', 'deposit_amount', 
                    'lease_duration_months', 'notice_period_days', 'utilities_included',
                    'maintenance_fee', 'rental_increase_percentage'],
        },
        'hidden_fields': [
            'land_size_hectares', 'land_size_acres', 'land_use', 'zoning',
            'soil_type', 'topography', 'water_access', 'electricity_access',
            'road_access', 'development_potential',
            'commercial_type', 'number_of_floors', 'parking_available',
            'loading_bays', 'ceiling_height',
            'student_accommodation_type', 'semester_duration_months',
            'is_per_student_pricing', 'per_student_price', 'includes_meals',
            'includes_internet', 'includes_study_area', 'proximity_to_campus',
            'shuttle_service', 'security_guards', 'cctv_cameras',
            'bond_available', 'transfer_duty', 'registration_fees',
            'maximum_stay'
        ],
        'field_labels': {
            'stay_type': 'Rental Type',
            'minimum_stay': 'Minimum Stay (days)',
            'booking_unit': 'Price Per',
            'deposit_amount': 'Deposit Amount (ZAR)',
            'lease_duration_months': 'Lease Duration (months)',
            'notice_period_days': 'Notice Period (days)',
            'utilities_included': 'Utilities Included',
            'maintenance_fee': 'Monthly Maintenance Fee (ZAR)',
            'rental_increase_percentage': 'Annual Rental Increase (%)',
        },
        'field_placeholders': {
            'minimum_stay': 'e.g., 90',
            'deposit_amount': 'e.g., 15000',
            'lease_duration_months': 'e.g., 12',
            'notice_period_days': 'e.g., 30',
            'maintenance_fee': 'e.g., 500',
            'rental_increase_percentage': 'e.g., 5',
        },
        'field_help_texts': {
            'minimum_stay': 'Minimum rental period in days',
            'lease_duration_months': 'Fixed lease duration (leave blank for open-ended)',
        },
        'show_pricing_options': True,
        'show_booking_options': True,
        'show_lease_options': True,
        'show_sale_options': False,
        'sections': ['Basic Information', 'Rental Details'],
        'default_status': 'available',
        'listing_types': ['rent', 'lease'],
        'requires_land_fields': False,
        'stay_type_default': 'monthly',
        'booking_unit_default': 'month',
        'minimum_stay_default': 90,
    },
    'residential_sale': {
        'title': 'Residential for Sale',
        'icon': 'fa-home',
        'badge_color': 'success',
        'description': 'List houses and apartments for sale',
        'required_fields': ['title', 'description', 'price', 'location'],
        'show_fields': {
            'basic': ['title', 'description', 'price', 'location', 'bedrooms', 'bathrooms'],
            'sale': ['bond_available', 'transfer_duty', 'registration_fees', 'levies', 'rates_taxes'],
        },
        'hidden_fields': [
            'land_size_hectares', 'land_size_acres', 'land_use', 'zoning',
            'soil_type', 'topography', 'water_access', 'electricity_access',
            'road_access', 'development_potential',
            'commercial_type', 'number_of_floors', 'parking_available',
            'loading_bays', 'ceiling_height',
            'student_accommodation_type', 'semester_duration_months',
            'is_per_student_pricing', 'per_student_price',
            'minimum_stay', 'maximum_stay', 'stay_type', 'booking_unit',
            'deposit_amount', 'lease_duration_months', 'notice_period_days',
            'utilities_included', 'maintenance_fee', 'rental_increase_percentage',
            'pets_allowed'
        ],
        'field_labels': {
            'bond_available': 'Bond / Finance Available',
            'transfer_duty': 'Transfer Duty (ZAR)',
            'registration_fees': 'Registration Fees (ZAR)',
            'levies': 'Monthly Levies (ZAR)',
            'rates_taxes': 'Annual Rates & Taxes (ZAR)',
        },
        'field_placeholders': {
            'transfer_duty': 'e.g., 50000',
            'registration_fees': 'e.g., 15000',
            'levies': 'e.g., 1200',
            'rates_taxes': 'e.g., 5000',
        },
        'field_help_texts': {
            'levies': 'Monthly body corporate or estate levies',
        },
        'show_pricing_options': True,
        'show_booking_options': False,
        'show_lease_options': False,
        'show_sale_options': True,
        'sections': ['Basic Information', 'Sale Details'],
        'default_status': 'available',
        'listing_types': ['sale'],
        'requires_land_fields': False,
    },
    'commercial_lease': {
        'title': 'Commercial for Lease',
        'icon': 'fa-building',
        'badge_color': 'dark',
        'description': 'List commercial spaces and offices for lease',
        'required_fields': ['title', 'description', 'price', 'location', 'commercial_type'],
        'show_fields': {
            'basic': ['title', 'description', 'price', 'location'],
            'commercial': ['commercial_type', 'number_of_floors', 'parking_available', 
                          'loading_bays', 'ceiling_height', 'commercial_zone'],
            'lease': ['deposit_amount', 'lease_duration_months', 'notice_period_days',
                     'utilities_included', 'maintenance_fee'],
        },
        'hidden_fields': [
            'land_size_hectares', 'land_size_acres', 'land_use', 'zoning',
            'soil_type', 'topography', 'water_access', 'electricity_access',
            'road_access', 'development_potential',
            'student_accommodation_type', 'semester_duration_months',
            'is_per_student_pricing', 'per_student_price',
            'minimum_stay', 'maximum_stay', 'stay_type', 'booking_unit',
            'bond_available', 'transfer_duty', 'registration_fees',
            'bedrooms', 'bathrooms', 'garages', 'pets_allowed', 'furnishing_status'
        ],
        'field_labels': {
            'commercial_type': 'Commercial Property Type',
            'number_of_floors': 'Number of Floors',
            'parking_available': 'Parking Spaces',
            'loading_bays': 'Loading Bays',
            'ceiling_height': 'Ceiling Height (m)',
            'commercial_zone': 'Commercial Zone',
            'deposit_amount': 'Deposit Amount (ZAR)',
            'lease_duration_months': 'Lease Duration (months)',
            'notice_period_days': 'Notice Period (days)',
            'utilities_included': 'Utilities Included',
            'maintenance_fee': 'Monthly Maintenance Fee (ZAR)',
        },
        'field_placeholders': {
            'parking_available': 'e.g., 20',
            'loading_bays': 'e.g., 2',
            'ceiling_height': 'e.g., 4.5',
            'deposit_amount': 'e.g., 100000',
            'lease_duration_months': 'e.g., 24',
            'notice_period_days': 'e.g., 60',
            'maintenance_fee': 'e.g., 2000',
        },
        'field_help_texts': {
            'parking_available': 'Number of parking spaces available',
            'lease_duration_months': 'Fixed lease duration (leave blank for negotiable)',
        },
        'show_pricing_options': True,
        'show_booking_options': False,
        'show_lease_options': True,
        'show_sale_options': False,
        'sections': ['Basic Information', 'Commercial Details', 'Lease Details'],
        'default_status': 'available',
        'listing_types': ['lease', 'rent'],
        'requires_land_fields': False,
    },
}

def get_property_config(purpose):
    """Get configuration for a specific property purpose"""
    return PROPERTY_CONFIGS.get(purpose, PROPERTY_CONFIGS.get('residential_sale'))

def get_all_purposes():
    """Get all available property purposes with their labels and icons"""
    return [
        ('land_sale', 'Land for Sale', 'fa-map', 'success'),
        ('residential_sale', 'Residential for Sale', 'fa-home', 'success'),
        ('long_stay', 'Long Stay / Rental', 'fa-home', 'primary'),
        ('short_stay', 'Short Stay / Vacation', 'fa-bed', 'warning'),
        ('student_accommodation', 'Student Accommodation', 'fa-graduation-cap', 'info'),
        ('commercial_lease', 'Commercial for Lease', 'fa-building', 'dark'),
    ]

def should_show_field(purpose, field_name):
    """Check if a field should be shown for a given purpose"""
    config = get_property_config(purpose)
    if not config:
        return True
    
    if field_name in config.get('hidden_fields', []):
        return False
    
    for section, fields in config.get('show_fields', {}).items():
        if field_name in fields:
            return True
    
    basic_fields = ['title', 'description', 'price', 'location', 'bedrooms', 'bathrooms', 'garages']
    if field_name in basic_fields:
        return True
    
    return True