# Generated by Django 5.2.6 on 2026-07-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_maintenancecategory_maintenancerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='route_path',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='accuracy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='heading',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='current_occupancy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='custom_category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='maximum_stay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='minimum_stay',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pricing_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_count',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('triple', 'Triple Room'), ('suite', 'Suite'), ('studio', 'Studio'), ('apartment', 'Apartment Unit'), ('office', 'Office Space'), ('retail', 'Retail Unit'), ('warehouse', 'Warehouse Unit'), ('storage', 'Storage Unit'), ('common', 'Common Area'), ('meeting', 'Meeting Room'), ('conference', 'Conference Room'), ('function', 'Function Room'), ('dormitory', 'Dormitory'), ('other', 'Other')], default='single', max_length=20),
        ),
    ]
