# Generated by Django 5.2.6 on 2026-07-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_booking_guest_details_alter_booking_route_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_details',
            field=models.JSONField(blank=True, default=dict, help_text='Guest information if not user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='route_path',
            field=models.JSONField(blank=True, default=list, help_text='GPS route points'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_distance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance in kilometers', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_duration',
            field=models.PositiveIntegerField(default=0, help_text='Trip duration in minutes'),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='accuracy',
            field=models.PositiveIntegerField(default=0, help_text='Accuracy in meters'),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='heading',
            field=models.PositiveIntegerField(default=0, help_text='Heading in degrees'),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Speed in km/h', max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='current_occupancy',
            field=models.PositiveIntegerField(default=0, help_text='Current number of people in property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='custom_category_name',
            field=models.CharField(blank=True, help_text='If property type not available', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Additional custom fields'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Floor area in sq meters', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Property is currently available for instant booking'),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Land area in sq meters', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Last time property sent heartbeat signal', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum capacity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=1, help_text='Maximum people that can occupy'),
        ),
        migrations.AlterField(
            model_name='property',
            name='maximum_stay',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum stay in booking_unit', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='minimum_stay',
            field=models.PositiveIntegerField(default=1, help_text='Minimum stay in booking_unit'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per room/unit', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pricing_details',
            field=models.JSONField(blank=True, default=dict, help_text='Tiered or dynamic pricing details'),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_count',
            field=models.JSONField(blank=True, default=dict, help_text='Count by room type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total area in sq meters', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Total number of rooms/units'),
        ),
        migrations.AlterField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text='Virtual tour link (YouTube, Matterport, etc.)'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom fields for this category'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System default category'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='User-created feature'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_types',
            field=models.JSONField(blank=True, default=list, help_text='Types of beds available'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_accessible',
            field=models.BooleanField(default=False, help_text='Wheelchair accessible'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin R1oom'), ('triple', 'Triple Room'), ('suite', 'Suite'), ('studio', 'Studio'), ('apartment', 'Apartment Unit'), ('office', 'Office Space'), ('retail', 'Retail Unit'), ('warehouse', 'Warehouse Unit'), ('storage', 'Storage Unit'), ('common', 'Common Area'), ('meeting', 'Meeting Room'), ('conference', 'Conference Room'), ('function', 'Function Room'), ('dormitory', 'Dormitory'), ('other', 'Other')], default='single', max_length=20),
        ),
    ]
