# Generated by Django 5.2.6 on 2026-08-13 00:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_agentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('follower', 'Follower'), ('saved', 'Saved Agent'), ('client', 'Client'), ('past_client', 'Past Client'), ('referral', 'Referral Partner'), ('collaborator', 'Collaborator')], default='follower', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('knowledge', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('responsiveness', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('negotiation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('review_title', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('agent_response', models.TextField(blank=True)),
                ('agent_response_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSocialShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('signal', 'Signal'), ('viber', 'Viber'), ('wechat', 'WeChat'), ('line', 'LINE'), ('email', 'Email'), ('copy', 'Copy Link'), ('other', 'Other')], max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('code3', models.CharField(blank=True, max_length=3)),
                ('calling_code', models.CharField(max_length=10, unique=True)),
                ('flag', models.CharField(blank=True, help_text='Emoji flag', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='agentprofile',
            name='realestate__city_212a55_idx',
        ),
        migrations.RenameField(
            model_name='agentprofile',
            old_name='province',
            new_name='state_province',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='century21_url',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='remax_url',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='areas_served',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='bayut_url',
            field=models.CharField(blank=True, help_text='Bayut URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='discord_username',
            field=models.CharField(blank=True, help_text='Discord username#tag', max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='domaincomau_url',
            field=models.CharField(blank=True, help_text='domain.com.au URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='dubizzle_url',
            field=models.CharField(blank=True, help_text='Dubizzle URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='kakao_id',
            field=models.CharField(blank=True, help_text='KakaoTalk ID', max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='line_id',
            field=models.CharField(blank=True, help_text='LINE ID', max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='onthemarket_url',
            field=models.CharField(blank=True, help_text='OnTheMarket Profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='properati_url',
            field=models.CharField(blank=True, help_text='Properati URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='properties_listed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='propertyfinder_url',
            field=models.CharField(blank=True, help_text='Property Finder URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='propertyguru_url',
            field=models.CharField(blank=True, help_text='PropertyGuru URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='realestatecomau_url',
            field=models.CharField(blank=True, help_text='realestate.com.au URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='reddit_url',
            field=models.CharField(blank=True, help_text='Reddit URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='redfin_url',
            field=models.CharField(blank=True, help_text='Redfin Profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='rightmove_url',
            field=models.CharField(blank=True, help_text='Rightmove Profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='rumah123_url',
            field=models.CharField(blank=True, help_text='Rumah123 URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='signal_number',
            field=models.CharField(blank=True, help_text='Signal number', max_length=30),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='timezone',
            field=models.CharField(blank=True, default='Africa/Johannesburg', max_length=50),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='trulia_url',
            field=models.CharField(blank=True, help_text='Trulia Profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='viber_number',
            field=models.CharField(blank=True, help_text='Viber number', max_length=30),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='vivareal_url',
            field=models.CharField(blank=True, help_text='VivaReal URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='zoopla_url',
            field=models.CharField(blank=True, help_text='Zoopla Profile URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='agency_logo',
            field=models.ImageField(blank=True, null=True, upload_to='agent_logos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='agent_type',
            field=models.CharField(choices=[('independent', 'Independent Agent'), ('agency', 'Agency Agent'), ('broker', 'Broker'), ('property_manager', 'Property Manager'), ('developer', 'Developer'), ('consultant', 'Real Estate Consultant'), ('commercial', 'Commercial Agent'), ('residential', 'Residential Agent'), ('student_housing', 'Student Housing Specialist'), ('luxury', 'Luxury Property Specialist'), ('international', 'International Property Specialist'), ('corporate', 'Corporate Real Estate'), ('investment', 'Investment Property Specialist'), ('custom', 'Custom (Specify Below)')], default='independent', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='custom_agent_type',
            field=models.CharField(blank=True, help_text="If 'Custom' selected, specify your agent type", max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='facebook_url',
            field=models.CharField(blank=True, help_text='Facebook URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='glassdoor_url',
            field=models.CharField(blank=True, help_text='Glassdoor Profile URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='indeed_url',
            field=models.CharField(blank=True, help_text='Indeed Profile URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='instagram_url',
            field=models.CharField(blank=True, help_text='Instagram URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Real Estate License Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, help_text='LinkedIn URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='max_price_focus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='min_price_focus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='phone_primary',
            field=models.CharField(blank=True, help_text='Primary phone (any format, smart detection)', max_length=30),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='phone_secondary',
            field=models.CharField(blank=True, help_text='Secondary phone', max_length=30),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='pinterest_url',
            field=models.CharField(blank=True, help_text='Pinterest URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='privateproperty_url',
            field=models.CharField(blank=True, help_text='PrivateProperty Profile URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='property24_url',
            field=models.CharField(blank=True, help_text='Property24 Profile URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='realtor_url',
            field=models.CharField(blank=True, help_text='Realtor.com Profile URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='services_offered',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='snapchat_url',
            field=models.CharField(blank=True, help_text='Snapchat URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram @username', max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='tiktok_url',
            field=models.CharField(blank=True, help_text='TikTok URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='total_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='twitter_url',
            field=models.CharField(blank=True, help_text='Twitter/X URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='website',
            field=models.CharField(blank=True, help_text="Website (any format, we'll clean it)", max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number (any format)', max_length=30),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='youtube_url',
            field=models.CharField(blank=True, help_text='YouTube URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='zillow_url',
            field=models.CharField(blank=True, help_text='Zillow Profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentconnection',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='realestate.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentreview',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='realestate.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentreview',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.booking'),
        ),
        migrations.AddField(
            model_name='agentreview',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.property'),
        ),
        migrations.AddField(
            model_name='agentreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentsocialshare',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to='realestate.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentsocialshare',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_shares', to='realestate.property'),
        ),
        migrations.AddField(
            model_name='agentsocialshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['calling_code'], name='realestate__calling_c6099e_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['code'], name='realestate__code_b43ccb_idx'),
        ),
        migrations.AddField(
            model_name='agentsocialshare',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.country'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='license_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licensed_agents', to='realestate.country'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='realestate.country'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['city', 'state_province'], name='realestate__city_7043e1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['agent_type'], name='realestate__agent_t_1babef_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['country'], name='realestate__country_1e2142_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentconnection',
            unique_together={('agent', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='agentreview',
            unique_together={('agent', 'user')},
        ),
    ]
