# Generated by Django 5.2.6 on 2026-08-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_agentconnection_agentreview_agentsocialshare_country_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agentprofile',
            name='realestate__agent_t_1babef_idx',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='angellist_url',
            field=models.CharField(blank=True, help_text='AngelList Profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='crunchbase_url',
            field=models.CharField(blank=True, help_text='Crunchbase Profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='homescom_url',
            field=models.CharField(blank=True, help_text='Homes.com Profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='ninety_nine_co_url',
            field=models.CharField(blank=True, help_text='99.co URL', max_length=500),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='primelocation_url',
            field=models.CharField(blank=True, help_text='PrimeLocation Profile URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('triple', 'Triple Room'), ('suite', 'Suite'), ('studio', 'Studio'), ('apartment', 'Apartment Unit'), ('office', 'Office Space'), ('retail', 'Retail Unit'), ('warehouse', 'Warehouse Unit'), ('storage', 'Storage Unit'), ('common', 'Common Area'), ('meeting', 'Meeting Room'), ('conference', 'Conference Room'), ('function', 'Function Room'), ('dormitory', 'Dormitory'), ('other', 'Other')], default='single', max_length=20),
        ),
    ]
