# Generated by Django 5.2.6 on 2026-08-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_remove_agentprofile_realestate__agent_t_1babef_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
