# Generated by Django 5.2.6 on 2026-09-02 02:35

import realestate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_alter_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='agency_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='angellist_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='bayut_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='crunchbase_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='custom_agent_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='custom_specializations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='discord_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='domaincomau_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='dubizzle_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='email_primary',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='email_secondary',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='ffc_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='glassdoor_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='homescom_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='indeed_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='line_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='ninety_nine_co_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='onthemarket_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='pinterest_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='primelocation_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='privateproperty_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='properati_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='property24_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='propertyfinder_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='propertyguru_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='realestatecomau_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='realtor_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='reddit_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='redfin_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='rightmove_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='rumah123_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='signal_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='snapchat_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='tiktok_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='trulia_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='viber_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='vivareal_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='website',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='zillow_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='zoopla_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='route_path',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='accuracy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='heading',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='property',
            name='base_price',
            field=realestate.models.FlexiblePriceField(decimal_places=2, help_text='Base price for booking/rent/sale', max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='current_occupancy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='custom_category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='property',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='maximum_stay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='minimum_stay',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_sqm',
            field=realestate.models.FlexiblePriceField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_unit',
            field=realestate.models.FlexiblePriceField(blank=True, decimal_places=2, help_text='Price per room/unit', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pricing_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='property',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_count',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
