# Generated by Django 5.2.6 on 2026-09-06 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0006_applicantprofile_avatar'),
        ('realestate', '0010_alter_agentprofile_agency_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bond_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='cctv_cameras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='commercial_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='commercial_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New Development'), ('excellent', 'Excellent Condition'), ('good', 'Good Condition'), ('needs_renovation', 'Needs Renovation'), ('fixer_upper', 'Fixer Upper'), ('under_construction', 'Under Construction'), ('land_only', 'Land Only')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='development_potential',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='dynamic_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Store any additional dynamic fields'),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('furnished', 'Fully Furnished'), ('semi_furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished'), ('not_applicable', 'Not Applicable')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='includes_internet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='includes_meals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='includes_study_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='inverters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_per_student_pricing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen_facilities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='land_size_acres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_size_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_use',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='last_renovated',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Lease duration in months', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='levies',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly levies', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='loading_bays',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='notice_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='per_student_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='property_category',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('land', 'Land / Vacant'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('mixed_use', 'Mixed Use'), ('student_housing', 'Student Housing'), ('short_stay', 'Short Stay / Vacation'), ('hospitality', 'Hospitality'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_config_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_purpose',
            field=models.CharField(blank=True, choices=[('sale', 'For Sale'), ('rent', 'For Rent / Lease'), ('short_stay', 'Short Stay (Daily/Weekly)'), ('long_stay', 'Long Stay (Monthly/Semester/Yearly)'), ('permanent', 'Permanent Stay'), ('commercial_lease', 'Commercial Lease'), ('land_sale', 'Land Sale'), ('student_accommodation', 'Student Accommodation'), ('vacation_rental', 'Vacation Rental')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='proximity_to_campus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rates_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual rates and taxes', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='registration_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_increase_interval',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_increase_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='restaurant_equipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='road_access',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='security_guards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='semester_duration_months',
            field=models.PositiveIntegerField(blank=True, default=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='shuttle_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='signage_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='solar_panels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='stay_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('semester', 'Semester (6 months)'), ('yearly', 'Yearly'), ('permanent', 'Permanent'), ('flexible', 'Flexible / Negotiable'), ('not_applicable', 'Not Applicable')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='student_accommodation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='topography',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='transfer_duty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='utilities_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='water_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='water_tank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='booking_unit',
            field=models.CharField(blank=True, choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year'), ('semester', 'Per Semester'), ('once_off', 'Once Off')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='maximum_stay',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum stay in days (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='minimum_stay',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum stay in days (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pricing_structure',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('tiered', 'Tiered Pricing'), ('dynamic', 'Dynamic Pricing'), ('negotiable', 'Negotiable'), ('per_person', 'Per Person'), ('per_night', 'Per Night'), ('per_sqm', 'Per Square Meter')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='realestate.propertytype'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_purpose'], name='realestate__propert_895c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_category'], name='realestate__propert_2d4082_idx'),
        ),
    ]
