# Generated by Django 5.2.6 on 2026-09-27 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0006_applicantprofile_avatar'),
        ('realestate', '0011_property_bond_available_property_cctv_cameras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBookingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card / Yoco')], max_length=20)),
                ('gateway', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('yoco_checkout_id', models.CharField(blank=True, max_length=200)),
                ('redirect_url', models.URLField(blank=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='realestate.booking')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_booking_payments', to='hiring.businessprofile')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_booking_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_cash', models.BooleanField(default=True)),
                ('accept_card', models.BooleanField(default=True)),
                ('yoco_enabled', models.BooleanField(default=True)),
                ('yoco_merchant_reference', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_holder', models.CharField(blank=True, max_length=160)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('cheque', 'Cheque / Current'), ('savings', 'Savings'), ('business', 'Business'), ('transmission', 'Transmission')], default='cheque', max_length=20)),
                ('payout_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_payment_profile', to='hiring.businessprofile')),
            ],
        ),
    ]
