# Generated by Django 5.2.6 on 2026-08-18 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolapplication',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolapplication',
            name='guardian_id',
            field=models.FileField(blank=True, null=True, upload_to='school_applications/guardian_id/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='schoolapplication',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='school_applications/id_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='schoolapplication',
            name='motivation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
