# Generated by Django 5.2.6 on 2026-08-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_schoolapplication_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bursaryapplication',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schoolapplication',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='universityapplication',
            unique_together=set(),
        ),
    ]
