# Generated by Django 5.2.6 on 2026-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_bursaryapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursaryapplication',
            name='academic_average',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='academic_average',
            field=models.TextField(blank=True, null=True),
        ),
    ]
