# Generated by Django 5.2.6 on 2026-06-25 13:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(help_text='Upload video file (MP4, MOV, AVI, WEBM)', upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'webm'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('connections', 'Connections Only'), ('company', 'Company Only')], default='public', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('watch_time', models.BigIntegerField(default=0, help_text='Total watch time in seconds')),
                ('average_watch_percentage', models.FloatField(default=0, help_text='Average % of video watched')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'realestate_videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_video_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hiring.videocomment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hiring.video')),
            ],
            options={
                'db_table': 'realestate_video_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='realestate__created_292626_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['author', '-created_at'], name='realestate__author__d79500_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_published', 'privacy'], name='realestate__is_publ_3ae54e_idx'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['video', '-created_at'], name='realestate__video_i_04404a_idx'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['author', '-created_at'], name='realestate__author__8a029d_idx'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=models.Index(fields=['parent_comment', '-created_at'], name='realestate__parent__2bd7f5_idx'),
        ),
    ]
