# Generated by Django 5.2.6 on 2026-08-22 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_blogpost_career_contactmessage_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('cookies', 'Cookies Policy'), ('help', 'Help Center'), ('about', 'About Us'), ('contact', 'Contact Us'), ('faq', 'FAQ'), ('careers', 'Careers'), ('blog', 'Blog')], db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML content for the page. Use <h1>, <p>, <ul>, etc.')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=200)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO meta keywords', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sections', models.JSONField(blank=True, default=list, help_text='List of sections with title and content. Format: [{"title": "Section 1", "content": "Content here"}]')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_static_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['page_type'],
            },
        ),
    ]
