# Generated by Django 5.2.6 on 2026-08-28 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
