# Generated by Django 5.2.6 on 2026-09-29 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0006_applicantprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='pushsubscription',
            table=None,
        ),
    ]
