# Generated by Django 5.2.6 on 2026-10-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0007_alter_pushsubscription_auth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Help Center', max_length=160)),
                ('description', models.CharField(default='Find practical guides and answers about using OppoGlobe.', max_length=300)),
                ('content', models.TextField(blank=True, help_text='Optional HTML for additional help information.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Center page',
                'verbose_name_plural': 'Help Center pages',
            },
        ),
    ]
