# Generated by Django 5.2.6 on 2026-07-26 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiring', '0003_pushsubscription'),
        ('realestate', '0004_alter_booking_guest_details_alter_booking_route_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('job_application', 'Job Application'), ('job_alert', 'Job Alert'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('comment_reply', 'Comment Reply'), ('mention', 'Mention'), ('follow', 'Follow'), ('connection_request', 'Connection Request'), ('profile_view', 'Profile View'), ('property_created', 'Property Created'), ('property_updated', 'Property Updated'), ('property_booked', 'Property Booked'), ('property_inquiry', 'Property Inquiry'), ('property_review', 'Property Review'), ('property_wishlist', 'Property Wishlist'), ('property_status_change', 'Property Status Change'), ('maintenance_request', 'Maintenance Request'), ('maintenance_update', 'Maintenance Update'), ('booking_confirmation', 'Booking Confirmation'), ('booking_cancellation', 'Booking Cancellation'), ('room_available', 'Room Available'), ('bursary', 'Bursary Update'), ('university', 'University Update'), ('school', 'School Update'), ('application', 'Application Update'), ('system', 'System Notification'), ('message', 'Message'), ('reminder', 'Reminder'), ('newsletter', 'Newsletter'), ('promotion', 'Promotion')], default='system', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('formatted_message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('bursary_id', models.CharField(blank=True, max_length=100, null=True)),
                ('university_id', models.CharField(blank=True, max_length=100, null=True)),
                ('school_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_related_hiring', to='hiring.applicantprofile')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_related_hiring', to='hiring.application')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_related_realestate', to='realestate.booking')),
                ('business_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_related_hiring', to='hiring.businessprofile')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_related_hiring', to='hiring.comment')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_related_hiring', to='hiring.joblisting')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_related_realestate', to='realestate.maintenancerequest')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_related_hiring', to='hiring.post')),
                ('property_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_related_realestate', to='realestate.property')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_related_realestate', to='realestate.room')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('web', 'Web Browser'), ('mobile', 'Mobile App'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='web', max_length=20)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('registration_token', models.CharField(max_length=500)),
                ('endpoint', models.URLField(blank=True, max_length=500, null=True)),
                ('p256dh', models.CharField(blank=True, max_length=255, null=True)),
                ('auth', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_device_records',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('push', 'Push Notification'), ('sms', 'SMS')], default='in_app', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_log_records',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('email_application_updates', models.BooleanField(default=True)),
                ('email_bursary_updates', models.BooleanField(default=True)),
                ('email_university_updates', models.BooleanField(default=True)),
                ('email_school_updates', models.BooleanField(default=True)),
                ('email_job_alerts', models.BooleanField(default=True)),
                ('email_property_updates', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('in_app_application_updates', models.BooleanField(default=True)),
                ('in_app_bursary_updates', models.BooleanField(default=True)),
                ('in_app_university_updates', models.BooleanField(default=True)),
                ('in_app_school_updates', models.BooleanField(default=True)),
                ('in_app_job_alerts', models.BooleanField(default=True)),
                ('in_app_property_updates', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('sound_volume', models.IntegerField(default=70, help_text='Volume percentage 0-100')),
                ('selected_sound', models.CharField(choices=[('default', 'Default'), ('gentle', 'Gentle'), ('pop', 'Pop'), ('chime', 'Chime'), ('bell', 'Bell'), ('none', 'None')], default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_pref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_pref_records',
            },
        ),
        migrations.CreateModel(
            name='NotificationSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_enabled', models.BooleanField(default=True)),
                ('sound_volume', models.IntegerField(default=70, help_text='Volume percentage 0-100')),
                ('selected_sound', models.CharField(choices=[('default', 'Default'), ('gentle', 'Gentle'), ('pop', 'Pop'), ('chime', 'Chime'), ('bell', 'Bell'), ('none', 'None')], default='default', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sound_pref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_sound_records',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_6cad8f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_712c30_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_e1c0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_fee3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_a73a39_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', '-sent_at'], name='notificatio_recipie_61f7c2_idx'),
        ),
    ]
